### PR TITLE
[WFLY-13914] optional feature which adds maven repos from builder pom

### PR DESCRIPTION
**Pull request by emmartins**
Issue: https://issues.redhat.com/browse/WFLY-13914

### CODE REVIEW

**Comment by emmartins** [comment]
In plugin config if you add
 
<includeRepositories>
     <id>jboss-public-repository-group</id>
     <id>jboss-enterprise-maven-repository</id>
</includeRepositories>

it adds repos and plugin repos with listed IDs found in the model chain from builder pom.xml.

If instead you add <includeRepositories/> it adds all repos and plugin repos, and if no such config element then adds none.

@bstansberry sounds good?

**Comment by bstansberry** [comment]
@emmartins A possibly tricky thing is the settings for those repos in the base WF pom are parameterized using maven properties. What would happen with that?

The basic configuration scheme you propose (list repos, all repos or none) sounds good.

**Comment by emmartins** [comment]
@bstansberry from my tests on wildfly BOMs it resolves such properties

**Comment by bstansberry** [comment]
@emmartins OK, so the generated bom inlines the resolved values?

That seems ok. When I think about the use cases for using those properties I don't think they apply to a generated bom.

**Review by bstansberry — APPROVED** [review]

**Pull request merged**
